### ISSUE TITLE
Cannot enumerate printers on iOS

### ISSUE THREAD

**Issue by mrbelk** [Zebra/LinkOS-Xamarin-Samples#3]
I am having a very hard time enumerating bluetooth printers on iOS (iPhone 5, iOS 10.3.3, Xamarin.iOS 11.6.1.2).

I set up a "PrinterDiscovery" class as per the sample, but when I call the BluetoothDiscoverer.Current.FindPrinters(), it immediately fires the OnDiscoveryFinished event and never fires the OnFoundPrinter. I am doing the same thing in Android (this is a Xamarin.Forms project) and I can enumerate the available printers just fine.

Here is the code that I am using:

```csharp
		public async Task<List<Tuple<string, string>>> GetPairedPrinters()
		{
			IDiscoveryEventHandler btHandler = DiscoveryHandlerFactory.Current.GetInstance();

			List<Tuple<string, string>> _foundPrinters = new List<Tuple<string, string>>();

			var finished = false;

			btHandler = DiscoveryHandlerFactory.Current.GetInstance();
			btHandler.OnFoundPrinter += (handler, discoveredPrinter) => {
				IDiscoveredPrinterBluetooth btPrinter = discoveredPrinter as IDiscoveredPrinterBluetooth;

				_foundPrinters.Add(new Tuple<string, string>(btPrinter.Address, btPrinter.FriendlyName));
			};

			btHandler.OnDiscoveryFinished += (handler) => {
				finished = true;
			};

			btHandler.OnDiscoveryError += (handler, message) => {
				finished = true;
			};

			BluetoothDiscoverer.Current.FindPrinters(null, btHandler);

			await Task.Delay(500);

			while (!finished)
			{
				await Task.Delay(100);
			}

			return _foundPrinters;
		}
```

I'm completely baffled as to why this won't work on iOS. For the record, I am trying to connect to a QLn420 with the MFI chipset.

Thanks,
Matthew Belk

**Comment by mrbelk** [comment]
So I noticed that the LinkOS_SDK is not technically supported on an iPhone 5, so I tried the same thing on an iPhone 7 (iOS 11.2.1) and got the same result.

**Comment by mrbelk** [comment]
so, I was able to successfully compile and run the xamarin sample app on my iPhone 7. My actual app doesn't do anything any differently, so I am baffled as to why the difference in behavior.

**Comment by Robin-West** [comment]
Hi Matthew,
So the sample shows the printers enumerating and your app doesn't?  Or do neither of them enumerate the printers?

Robin

**Comment by mrbelk** [comment]
The sample app worked on my iPhone 7

Matthew Belk
BizSpeed, Inc
678-287-3315
________________________________

**Comment by Robin-West** [comment]
OK - Few things to check.
1. Did you pair the printer in the iOS settings?  I'm assuming you did due to the fact that the other app is working.
2. Did you update your info.plist file?  This is similar to an Android Manifest file for iOS.  See the [documentation here](http://techdocs.zebra.com/link-os/2-13/xamarin/) for details. In the **iOS Project Settings and Configuration** section. Or you can take a look at the file on the sample app.

**Comment by mrbelk** [comment]
this might be my oversight. I didn't transfer over the UISupportedExternalAcccessoryProtocols or the UIBackgroundMode keys from the info.plist

**Comment by mrbelk** [comment]
We can close this out because I'm an idiot. Everything looks good now. Thanks for pointing those plist entries out for me.

**Comment by Robin-West** [comment]
No Problem... The number of times I forgot the manifest or plist when doing live demo coding.... Not fun.
