### ISSUE TITLE
Issue running Xamarin.Android /Xamarin.Forms

### ISSUE THREAD

**Issue by starl1n** [Zebra/LinkOS-Xamarin-Samples#4]
Hi I just create an app in Xamarin.Forms, when I add the LinkOS sdk and try to run it this is what i get 

I don't do anything else, just get that error, what should I do?

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Tool exited with code: 2. Output: warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.apache.commons.validator.ValidatorResources$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

trouble writing output: Too many method references: 72030; max is 65536.
You may try using --multi-dex option.
References by package:
     7 android.accessibilityservice
    85 android.animation
   233 android.app
    19 android.bluetooth
   147 android.content
    23 android.content.pm
    98 android.content.res
    30 android.database
   191 android.graphics
   117 android.graphics.drawable
     3 android.graphics.drawable.shapes
     3 android.graphics.pdf
     3 android.hardware.display
    11 android.hardware.fingerprint
    13 android.hardware.usb
     5 android.location
   130 android.media
    17 android.media.browse
    92 android.media.session
    36 android.net
   177 android.os
    28 android.print
     5 android.print.pdf
     9 android.provider
   207 android.runtime
    10 android.service.media
     1 android.support.compat
     1 android.support.coreui
     1 android.support.coreutils
    30 android.support.design
   310 android.support.design.internal
  1650 android.support.design.widget
     1 android.support.fragment
   352 android.support.graphics.drawable
     1 android.support.graphics.drawable.animated
     1 android.support.mediacompat
   653 android.support.transition
    30 android.support.v4
    48 android.support.v4.accessibilityservice
    62 android.support.v4.animation
  1942 android.support.v4.app
   269 android.support.v4.content
     1 android.support.v4.content.pm
    54 android.support.v4.content.res
     3 android.support.v4.database
    63 android.support.v4.graphics
   256 android.support.v4.graphics.drawable
    19 android.support.v4.hardware.display
    65 android.support.v4.hardware.fingerprint
    74 android.support.v4.internal.view
   657 android.support.v4.media
  1068 android.support.v4.media.session
    98 android.support.v4.net
    76 android.support.v4.os
   105 android.support.v4.print
   102 android.support.v4.provider
   101 android.support.v4.text
    20 android.support.v4.text.util
   330 android.support.v4.util
  1875 android.support.v4.view
  1264 android.support.v4.view.accessibility
    29 android.support.v4.view.animation
  1360 android.support.v4.widget
  1375 android.support.v7.app
    30 android.support.v7.appcompat
    30 android.support.v7.cardview
    27 android.support.v7.content.res
   135 android.support.v7.graphics
    69 android.support.v7.graphics.drawable
   729 android.support.v7.media
    30 android.support.v7.mediarouter
     1 android.support.v7.palette
    30 android.support.v7.recyclerview
     3 android.support.v7.text
     2 android.support.v7.transition
   179 android.support.v7.util
   154 android.support.v7.view
   679 android.support.v7.view.menu
  4181 android.support.v7.widget
   124 android.support.v7.widget.helper
     5 android.support.v7.widget.util
    49 android.text
     6 android.text.method
     4 android.text.style
     3 android.text.util
    70 android.transition
    62 android.util
   690 android.view
   231 android.view.accessibility
    50 android.view.animation
     2 android.view.inputmethod
     6 android.webkit
   642 android.widget
    56 au.com.bytecode.opencsv
    31 au.com.bytecode.opencsv.bean
   137 com.fasterxml.jackson.annotation
   419 com.fasterxml.jackson.core
   164 com.fasterxml.jackson.core.base
    34 com.fasterxml.jackson.core.format
   156 com.fasterxml.jackson.core.io
   399 com.fasterxml.jackson.core.json
    96 com.fasterxml.jackson.core.sym
    25 com.fasterxml.jackson.core.type
   263 com.fasterxml.jackson.core.util
  1081 com.fasterxml.jackson.databind
    38 com.fasterxml.jackson.databind.annotation
   137 com.fasterxml.jackson.databind.cfg
   462 com.fasterxml.jackson.databind.deser
   231 com.fasterxml.jackson.databind.deser.impl
   601 com.fasterxml.jackson.databind.deser.std
    12 com.fasterxml.jackson.databind.exc
    51 com.fasterxml.jackson.databind.ext
   629 com.fasterxml.jackson.databind.introspect
   104 com.fasterxml.jackson.databind.jsonFormatVisitors
    12 com.fasterxml.jackson.databind.jsonschema
    62 com.fasterxml.jackson.databind.jsontype
   188 com.fasterxml.jackson.databind.jsontype.impl
    63 com.fasterxml.jackson.databind.module
   626 com.fasterxml.jackson.databind.node
   259 com.fasterxml.jackson.databind.ser
   222 com.fasterxml.jackson.databind.ser.impl
   585 com.fasterxml.jackson.databind.ser.std
   299 com.fasterxml.jackson.databind.type
   412 com.fasterxml.jackson.databind.util
    16 com.valegoconsulting.formsapp
    27 com.xamarin.forms.platform.android
     1 com.xamarin.formsviewgroup
    37 com.zebra.android.comm
    20 com.zebra.android.discovery
    56 com.zebra.android.printer
    44 com.zebra.android.printer.internal
     7 com.zebra.android.sgd
    40 com.zebra.sdk.certificate
    44 com.zebra.sdk.certificate.internal
   240 com.zebra.sdk.comm
   109 com.zebra.sdk.comm.internal
    56 com.zebra.sdk.comm.snmp.internal
    95 com.zebra.sdk.device
    19 com.zebra.sdk.device.internal
     6 com.zebra.sdk.graphics
    61 com.zebra.sdk.graphics.internal
   293 com.zebra.sdk.printer
    79 com.zebra.sdk.printer.discovery
   245 com.zebra.sdk.printer.discovery.internal
   524 com.zebra.sdk.printer.internal
   148 com.zebra.sdk.printer.operations.internal
    66 com.zebra.sdk.settings
   154 com.zebra.sdk.settings.internal
   128 com.zebra.sdk.util.fileConversion.internal
   317 com.zebra.sdk.util.internal
    48 com.zebra.sdk.weblink
     8 default
    15 java.beans
   263 java.io
   487 java.lang
     1 java.lang.annotation
     8 java.lang.ref
    77 java.lang.reflect
    72 java.math
   123 java.net
    41 java.nio
     4 java.nio.channels
    28 java.nio.charset
   120 java.security
   171 java.security.cert
    25 java.security.interfaces
    73 java.security.spec
    23 java.sql
    84 java.text
   414 java.util
    61 java.util.concurrent
    17 java.util.concurrent.atomic
     7 java.util.concurrent.locks
     4 java.util.jar
    21 java.util.regex
    26 java.util.zip
    63 javax.crypto
     8 javax.crypto.interfaces
    45 javax.crypto.spec
     5 javax.naming
    15 javax.naming.directory
     7 javax.net
    37 javax.net.ssl
     6 javax.security.auth.x500
     1 javax.swing
     1 javax.swing.tree
     4 javax.xml.datatype
     1 javax.xml.namespace
     9 javax.xml.parsers
   211 md5270abb39e60627f0f200893b490a1ade
    50 md57018357d52b54713cd814fbd5262dd1f
     8 md59261b2cc52838fd1389cc6dc63a2a099
     6 md5a7903531ac28e2eb4c8576cdf2655bda
   933 md5b60ffeb829f638581ab2bb9b1a7f4f3f
    16 md5e65884dc28cc50d6f47c86a442e3c55d
    19 mono
    19 mono.android
    12 mono.android.accessibilityservice
     6 mono.android.accounts
    52 mono.android.animation
   106 mono.android.app
     8 mono.android.bluetooth
    60 mono.android.content
    10 mono.android.database.sqlite
    18 mono.android.drm
    26 mono.android.gesture
     6 mono.android.graphics
     6 mono.android.graphics.drawable
    28 mono.android.hardware
    10 mono.android.hardware.display
    10 mono.android.hardware.input
    20 mono.android.inputmethodservice
    30 mono.android.location
   198 mono.android.media
    50 mono.android.media.audiofx
     6 mono.android.media.effect
     6 mono.android.media.midi
     6 mono.android.media.session
     6 mono.android.media.tv
     6 mono.android.net
    36 mono.android.net.nsd
    10 mono.android.net.sip
    56 mono.android.net.wifi.p2p
     6 mono.android.nfc
    30 mono.android.os
    30 mono.android.preference
     6 mono.android.renderscript
    38 mono.android.runtime
    18 mono.android.sax
    22 mono.android.speech
    12 mono.android.speech.tts
    42 mono.android.support.design.widget
    19 mono.android.support.transition
    12 mono.android.support.v4.app
    12 mono.android.support.v4.content
     6 mono.android.support.v4.media.session
     6 mono.android.support.v4.os
    64 mono.android.support.v4.view
    12 mono.android.support.v4.view.accessibility
    48 mono.android.support.v4.widget
    22 mono.android.support.v7.app
     6 mono.android.support.v7.graphics
     6 mono.android.support.v7.media
   110 mono.android.support.v7.widget
    10 mono.android.text
    14 mono.android.transition
   248 mono.android.view
    12 mono.android.view.accessibility
    10 mono.android.view.animation
     8 mono.android.view.textservice
    24 mono.android.webkit
   232 mono.android.widget
    12 mono.java.lang
     4 mono.java.util
    10 mono.javax.xml.transform
     7 opentk
    13 opentk.platform.android
     7 opentk_1_0
    13 opentk_1_0.platform.android
     1 org.apache.commons.beanutils
    10 org.apache.commons.collections
    12 org.apache.commons.digester
     1 org.apache.commons.digester.xmlrules
   387 org.apache.commons.io
    70 org.apache.commons.io.comparator
   173 org.apache.commons.io.filefilter
   253 org.apache.commons.io.input
    71 org.apache.commons.io.monitor
   195 org.apache.commons.io.output
   955 org.apache.commons.lang3
   574 org.apache.commons.lang3.builder
   120 org.apache.commons.lang3.concurrent
    23 org.apache.commons.lang3.event
    78 org.apache.commons.lang3.exception
   105 org.apache.commons.lang3.math
   184 org.apache.commons.lang3.mutable
   168 org.apache.commons.lang3.reflect
   385 org.apache.commons.lang3.text
    67 org.apache.commons.lang3.text.translate
   377 org.apache.commons.lang3.time
    50 org.apache.commons.lang3.tuple
     9 org.apache.commons.logging
   103 org.apache.commons.net
    36 org.apache.commons.net.bsd
     7 org.apache.commons.net.chargen
     6 org.apache.commons.net.daytime
     7 org.apache.commons.net.discard
     9 org.apache.commons.net.echo
     7 org.apache.commons.net.finger
   449 org.apache.commons.net.ftp
   130 org.apache.commons.net.ftp.parser
   142 org.apache.commons.net.imap
    77 org.apache.commons.net.io
   260 org.apache.commons.net.nntp
   120 org.apache.commons.net.ntp
    87 org.apache.commons.net.pop3
   127 org.apache.commons.net.smtp
   165 org.apache.commons.net.telnet
    82 org.apache.commons.net.tftp
     9 org.apache.commons.net.time
   121 org.apache.commons.net.util
     6 org.apache.commons.net.whois
   342 org.apache.commons.validator
   324 org.apache.commons.validator.routines
    56 org.apache.commons.validator.routines.checkdigit
    20 org.apache.commons.validator.util
   183 org.apache.http
     1 org.apache.http.annotation
    14 org.apache.http.concurrent
    63 org.apache.http.config
   114 org.apache.http.entity
   125 org.apache.http.entity.mime
    61 org.apache.http.entity.mime.content
   204 org.apache.http.impl
    17 org.apache.http.impl.entity
   195 org.apache.http.impl.io
    20 org.apache.http.impl.pool
    24 org.apache.http.io
   231 org.apache.http.message
   110 org.apache.http.params
    98 org.apache.http.pool
   195 org.apache.http.protocol
   106 org.apache.http.util
    21 org.bouncycastle.crypto
    44 org.bouncycastle.crypto.digests
    25 org.bouncycastle.crypto.engines
     2 org.bouncycastle.crypto.generators
     7 org.bouncycastle.crypto.params
     3 org.spongycastle
   786 org.spongycastle.asn1
    15 org.spongycastle.asn1.anssi
     1 org.spongycastle.asn1.bc
     1 org.spongycastle.asn1.bsi
   291 org.spongycastle.asn1.cmp
   420 org.spongycastle.asn1.cms
    14 org.spongycastle.asn1.cms.ecc
   166 org.spongycastle.asn1.crmf
    48 org.spongycastle.asn1.cryptopro
   157 org.spongycastle.asn1.dvcs
   141 org.spongycastle.asn1.eac
   148 org.spongycastle.asn1.esf
    58 org.spongycastle.asn1.ess
     1 org.spongycastle.asn1.gnu
     1 org.spongycastle.asn1.iana
    30 org.spongycastle.asn1.icao
     1 org.spongycastle.asn1.isismtt
    14 org.spongycastle.asn1.isismtt.ocsp
    68 org.spongycastle.asn1.isismtt.x509
     1 org.spongycastle.asn1.iso
     1 org.spongycastle.asn1.kisa
     1 org.spongycastle.asn1.microsoft
    25 org.spongycastle.asn1.misc
    13 org.spongycastle.asn1.mozilla
     9 org.spongycastle.asn1.nist
     1 org.spongycastle.asn1.ntt
   143 org.spongycastle.asn1.ocsp
     8 org.spongycastle.asn1.oiw
   251 org.spongycastle.asn1.pkcs
   103 org.spongycastle.asn1.sec
    22 org.spongycastle.asn1.smime
    40 org.spongycastle.asn1.teletrust
    48 org.spongycastle.asn1.tsp
    43 org.spongycastle.asn1.ua
    13 org.spongycastle.asn1.util
    66 org.spongycastle.asn1.x500
    54 org.spongycastle.asn1.x500.style
   804 org.spongycastle.asn1.x509
    47 org.spongycastle.asn1.x509.qualified
    20 org.spongycastle.asn1.x509.sigi
   183 org.spongycastle.asn1.x9
   182 org.spongycastle.cert
    12 org.spongycastle.cert.bc
    65 org.spongycastle.cert.cmp
   105 org.spongycastle.cert.crmf
     4 org.spongycastle.cert.crmf.bc
    67 org.spongycastle.cert.crmf.jcajce
    27 org.spongycastle.cert.dane
     6 org.spongycastle.cert.dane.fetcher
    77 org.spongycastle.cert.jcajce
   126 org.spongycastle.cert.ocsp
     4 org.spongycastle.cert.ocsp.jcajce
    29 org.spongycastle.cert.path
    37 org.spongycastle.cert.path.validations
    58 org.spongycastle.cert.selector
    10 org.spongycastle.cert.selector.jcajce
   582 org.spongycastle.cms
    62 org.spongycastle.cms.bc
   360 org.spongycastle.cms.jcajce
   147 org.spongycastle.crypto
    26 org.spongycastle.crypto.agreement
    59 org.spongycastle.crypto.agreement.jpake
    19 org.spongycastle.crypto.agreement.kdf
    41 org.spongycastle.crypto.agreement.srp
     8 org.spongycastle.crypto.commitments
   533 org.spongycastle.crypto.digests
   112 org.spongycastle.crypto.ec
    42 org.spongycastle.crypto.encodings
   712 org.spongycastle.crypto.engines
     9 org.spongycastle.crypto.examples
   203 org.spongycastle.crypto.generators
    54 org.spongycastle.crypto.io
    18 org.spongycastle.crypto.kems
   153 org.spongycastle.crypto.macs
   225 org.spongycastle.crypto.modes
    54 org.spongycastle.crypto.modes.gcm
    44 org.spongycastle.crypto.paddings
   342 org.spongycastle.crypto.params
     4 org.spongycastle.crypto.parsers
    97 org.spongycastle.crypto.prng
    62 org.spongycastle.crypto.prng.drbg
   139 org.spongycastle.crypto.signers
  1324 org.spongycastle.crypto.tls
    65 org.spongycastle.crypto.util
    82 org.spongycastle.dvcs
    22 org.spongycastle.eac
    19 org.spongycastle.eac.jcajce
     6 org.spongycastle.eac.operator
    46 org.spongycastle.eac.operator.jcajce
    67 org.spongycastle.i18n
    16 org.spongycastle.i18n.filter
   141 org.spongycastle.jcajce
    20 org.spongycastle.jcajce.io
    53 org.spongycastle.jcajce.provider.asymmetric
    94 org.spongycastle.jcajce.provider.asymmetric.dh
    88 org.spongycastle.jcajce.provider.asymmetric.dsa
    82 org.spongycastle.jcajce.provider.asymmetric.dstu
   202 org.spongycastle.jcajce.provider.asymmetric.ec
    77 org.spongycastle.jcajce.provider.asymmetric.ecgost
    83 org.spongycastle.jcajce.provider.asymmetric.elgamal
    71 org.spongycastle.jcajce.provider.asymmetric.gost
    27 org.spongycastle.jcajce.provider.asymmetric.ies
   215 org.spongycastle.jcajce.provider.asymmetric.rsa
    86 org.spongycastle.jcajce.provider.asymmetric.util
   134 org.spongycastle.jcajce.provider.asymmetric.x509
    19 org.spongycastle.jcajce.provider.config
   291 org.spongycastle.jcajce.provider.digest
     6 org.spongycastle.jcajce.provider.keystore
    47 org.spongycastle.jcajce.provider.keystore.bc
    47 org.spongycastle.jcajce.provider.keystore.pkcs12
   608 org.spongycastle.jcajce.provider.symmetric
   165 org.spongycastle.jcajce.provider.symmetric.util
    16 org.spongycastle.jcajce.provider.util
    60 org.spongycastle.jcajce.spec
    63 org.spongycastle.jcajce.util
   182 org.spongycastle.jce
    11 org.spongycastle.jce.exception
    31 org.spongycastle.jce.interfaces
    17 org.spongycastle.jce.netscape
   631 org.spongycastle.jce.provider
   114 org.spongycastle.jce.spec
    31 org.spongycastle.math
   517 org.spongycastle.math.ec
    69 org.spongycastle.math.ec.custom.djb
  1759 org.spongycastle.math.ec.custom.sec
    23 org.spongycastle.math.ec.endo
    19 org.spongycastle.math.ec.tools
    29 org.spongycastle.math.field
   356 org.spongycastle.math.raw
    12 org.spongycastle.mozilla
     5 org.spongycastle.mozilla.jcajce
   100 org.spongycastle.openssl
    15 org.spongycastle.openssl.bc
    80 org.spongycastle.openssl.jcajce
    94 org.spongycastle.operator
   121 org.spongycastle.operator.bc
   128 org.spongycastle.operator.jcajce
    72 org.spongycastle.pkcs
    50 org.spongycastle.pkcs.bc
    74 org.spongycastle.pkcs.jcajce
     5 org.spongycastle.pkix
     5 org.spongycastle.pkix.jcajce
    83 org.spongycastle.pqc.asn1
    14 org.spongycastle.pqc.crypto
   118 org.spongycastle.pqc.crypto.gmss
    22 org.spongycastle.pqc.crypto.gmss.util
   144 org.spongycastle.pqc.crypto.mceliece
   149 org.spongycastle.pqc.crypto.ntru
    53 org.spongycastle.pqc.crypto.rainbow
    32 org.spongycastle.pqc.crypto.rainbow.util
    25 org.spongycastle.pqc.jcajce.provider
     9 org.spongycastle.pqc.jcajce.provider.gmss
   184 org.spongycastle.pqc.jcajce.provider.mceliece
    55 org.spongycastle.pqc.jcajce.provider.rainbow
    81 org.spongycastle.pqc.jcajce.provider.util
   100 org.spongycastle.pqc.jcajce.spec
   600 org.spongycastle.pqc.math.linearalgebra
     4 org.spongycastle.pqc.math.ntru.euclid
   168 org.spongycastle.pqc.math.ntru.polynomial
    19 org.spongycastle.pqc.math.ntru.util
   135 org.spongycastle.tsp
    64 org.spongycastle.tsp.cms
   170 org.spongycastle.util
    70 org.spongycastle.util.encoders
    28 org.spongycastle.util.io
    33 org.spongycastle.util.io.pem
    52 org.spongycastle.util.test
    15 org.spongycastle.voms
   463 org.spongycastle.x509
    12 org.spongycastle.x509.extension
    33 org.spongycastle.x509.util
    14 org.w3c.dom
     2 org.w3c.dom.bootstrap
     2 org.w3c.dom.ls
     5 org.xml.sax
     6 org.xml.sax.helpers
    14 org.xmlpull.v1
   386 uk.co.westhawk.snmp.beans
    38 uk.co.westhawk.snmp.event
    34 uk.co.westhawk.snmp.net
   204 uk.co.westhawk.snmp.pdu
   892 uk.co.westhawk.snmp.stack
    31 uk.co.westhawk.snmp.util
 (FormsApp.Droid)

**Comment by Robin-West** [comment]
Hi,
For now the way to fix this should be to enable Multi-Dex (in the project settings).  You could also try targeting an older framework.  We have alerted the product team that this Xamarin library should be recompiled to match the latest Android framework specifications.
Robin

**Comment by starl1n** [comment]
Thank you @Robin-West for the fast answer! and yes, that solves the issue. 

Thank you so much!
